{
    'name': 'Magento2 Product',
    'version': '15.0',
    'category': 'Extra Tools',
    'author': '',
    'depends': ['base', 'product', 'magento2', 'stock'],
    'data': ['security/ir.model.access.csv',
             'views/product_template.xml',
             'views/ptal.xml',
             'wizard/fetch_products_wiz.xml',
             ],
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'installable': True,
    'auto_install': False,
    'application': False,
}
